- id: format-python
  name: Format Python
  description: Format NOLS Python code using black, isort, docformatter
  entry: format_python_code.py
  types: [python]
  language: python
  language_version: python3
