# This is not an example config file, it is for this project.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: check-ast
        types: [python]
      - id: debug-statements
        types: [python]

  - repo: https://github.com/prettier/prettier
    rev: 1.18.2
    hooks:
      - id: prettier
        exclude: ^.*.min.js$ # skip minified libraries
        files: "\\.(\
          css|less|scss\
          |js|jsx\
          |json\
          |md|markdown|mdown|mkdn\
          |mdx\
          |ts|tsx\
          |vue\
          )$"
        args:
          - --prose-wrap=always
          - --print-width=100
          - --single-quote
          - --end-of-line=lf
