repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: check-ast
        types: [python]
      - id: debug-statements
        types: [python]

  - repo: https://github.com/NationalOutdoorLeadershipSchool/format-code
    rev: v0.5.0
    hooks:
      - id: format-python
        types: [python]
        language_version: python3.7

# TODO ech 2019-03-02 - update to use the format-javascript hook
#  - repo: https://github.com/prettier/prettier
#    rev: master
#    hooks:
#      - id: prettier
#        types: [javascript]
#        exclude: ^.*.min.js$ # skip minified libraries
#        args:
#          - --print-width=100
#          - --single-quote
#          - --end-of-line=lf
