# This is an example of settings for a typical NOLS project.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: check-ast
        types: [python]
      - id: debug-statements
        types: [python]

  - repo: https://github.com/NationalOutdoorLeadershipSchool/format-code
    rev: v0.8.0
    hooks:
      - id: format-python
        types: [python]
        language_version: python3.7

  - repo: https://github.com/prettier/prettier
    rev: 1.16.2
    hooks:
      - id: prettier
        exclude: ^.*.min.js$ # skip minified libraries
        files: "\\.(\
          css|less|scss\
          |js|jsx\
          |json\
          |md|markdown|mdown|mkdn\
          |mdx\
          |ts|tsx\
          |vue\
          |yaml|yml\
          )$"
        args:
          - --print-width=100
          - --single-quote
          - --end-of-line=lf
